from selenium import webdriver
import unittest
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
import time

class using_unitest(unittest.TestCase):

	def setUp(self):
		self.driver = webdriver.Chrome(executable_path=r"C:\Users\zorobabel\AppData\Local\Programs\Python\Python38\chromedriver.exe")
		self.driver.implicitly_wait(30)
		self.driver.maximize_window()

	def test_Login(self):
		driver = self.driver
		driver.get("https://ksms.mx/libertadqa/login")
		buscar_user = driver.find_element_by_id("username")
		buscar_password = driver.find_element_by_id("password")
		buscar_user.send_keys("tester")
		buscar_password.send_keys("Mexico.2081")
		submit = driver.find_element_by_xpath("//*[@id='loginForm']/div/button")
		submit.click()
		##inicia paso 1
	def step1(self):
		driver = self.driver
		perfil = driver.find_element_by_xpath("//*[@id='barraIconos']/div[5]/div[1]/div/div/div/a/img")
		perfil.click()
		type_client = driver.find_element_by_id("clienteNo")
		type_client.click()
		seleccionar = Select(driver.find_element_by_xpath("//*[@id='tipoDeDocumento']"))
		seleccionar.select_by_value("16")
		siguiente = driver.find_element_by_id("avanzarPerfilador")
		siguiente.click()
		nombre = driver.find_element_by_id("cliente_nombre")
		segundo_nombre = driver.find_element_by_id("cliente_segundoNombre")
		apellido_paterno = driver.find_element_by_id("cliente_apellidoPaterno")
		apellido_materno = driver.find_element_by_id("cliente_apellidoMaterno")
		correo = driver.find_element_by_xpath("//*[@id='emailCliente_emailPersonal']")
		celular = driver.find_element_by_xpath("//*[@id='telefonoCliente_telefonoCelular']")
		codigo = driver.find_element_by_xpath("//*[@id='cliente_codigoVerificacion']")
		tel_casa = driver.find_element_by_xpath("//*[@id='telefonoCliente_telefonoCasa']")
		nombre.send_keys("Luis")
		segundo_nombre.send_keys("Gustavo")
		apellido_paterno.send_keys("Revilla")
		apellido_materno.send_keys("Belmont")
		correo.send_keys("lgrevillabelmont@gmail.com")
		celular.send_keys(74-11-23-46-92)
		#time.sleep(5)
		codigo.click()
		confirmar = driver.find_element_by_xpath("//*[@id='barraIconos']/div[12]/div[7]/div/button")
		confirmar.click()
		codigo.send_keys("08680")
		tel_casa.send_keys("95-35-20-21-14")
		dia_nac = Select(driver.find_element_by_xpath("//*[@id='cliente_fechaDeNacimiento_dia']"))
		time.sleep(1)
		dia_nac.select_by_value("18")
		mes_nac = Select(driver.find_element_by_xpath("//*[@id='cliente_fechaDeNacimiento_mes']"))
		time.sleep(1)
		mes_nac.select_by_value("4")
		año_nac = Select(driver.find_element_by_xpath("//*[@id='cliente_fechaDeNacimiento_anio']"))
		time.sleep(1)
		año_nac.select_by_value("1999")
		sexo = Select(driver.find_element_by_xpath("//*[@id='cliente_genero']"))
		time.sleep(1)
		sexo.select_by_value("1")
		nacionalidad = Select(driver.find_element_by_xpath("//*[@id='cliente_nacionalidad']"))
		time.sleep(1)
		nacionalidad.select_by_value("1")
		estado = Select(driver.find_element_by_xpath("//*[@id='cliente_lugarDeNacimiento']"))
		time.sleep(1)
		estado.select_by_value("20")
		time.sleep(2)
		avanzar = driver.find_element_by_xpath("//*[@id='siguiente']")
		time.sleep(5)
		calle = driver.find_element_by_xpath("//*[@id='direccionCliente_calle']")
		numero = driver.find_element_by_xpath("//*[@id='direccionCliente_numeroExterior']")
		codigo_postal = driver.find_element_by_xpath("//*[@id='direccionCliente_codigoPostal']")
		calle.send_keys("Allende")
		numero.send_keys("11")
		codigo_postal.send_keys("69171")
		time.sleep(4)
		mes_vivienda = Select(driver.find_element_by_name("direccionCliente_tiempoDeVivir_mes"))
		time.sleep(1)
		mes_vivienda.select_by_value("4")
		año_vivienda = Select(driver.find_element_by_name("'direccionCliente_tiempoDeVivir_anio"))
		time.sleep(1)
		año_vivienda.select_by_value("2005")
		mes_ciudad = Select(driver.find_element_by_xpath("//*[@id='direccionCliente_tiempoDeResidencia']"))
		time.sleep(1)
		mes_ciudad.select_by_value("4")
		año_ciudad = Select(driver.find_element_by_xpath("/html/body/div[5]/div[3]/div/div[2]/form/div/div/div/fieldset/div[3]/div/div[3]/div/select[2]"))
		time.sleep(1)
		año_ciudad.select_by_value("2000")
		dependientes = Select(driver.find_element_by_xpath("//*[@id='cliente_dependientesEconomicos']"))
		time.sleep(1)
		dependientes.select_by_value("2")
		horario = Select(driver.find_element_by_xpath("//*[@id='direccionCliente_horarioDeContacto']"))
		time.sleep(1)
		horario.select_by_value("1")
		vivienda = Select(driver.find_element_by_xpath("//*[@id='direccionCliente_tipoDeVivienda']"))
		time.sleep(1)
		vivienda.select_by_value("1")
		estado_civil = Select(driver.find_element_by_xpath("//*[@id='cliente_estadoCivil']"))
		time.sleep(1)
		estado_civil.select_by_value("1")
		ir_empleo = driver.find_element_by_xpath("//*[@id='siguiente']")
		time.sleep(5)
		profesion = Select(driver.find_element_by_xpath("//*[@id='empleoCliente_profesion']"))
		time.sleep(5)
		profesion.select_by_value("110")
		ocupacion = Select(driver.find_element_by_xpath("//*[@id='empleoCliente_ocupacion']"))
		time.sleep(3)
		ocupacion.select_by_value("66")
		empresa = driver.find_element_by_xpath("//*[@id='empleoCliente_empresa']")
		empresa.send_keys("Kosmos")
		mes_empresa = Select(driver.find_element_by_name("empleoCliente_antiguedad_mes"))
		time.sleep("2")
		mes_empresa.select_by_value("4")
		año_empresa = Select(driver.find_element_by_name("empleoCliente_antiguedad_anio"))
		time.sleep("1")
		año_empresa.select_by_value("2014")
		ingresos_fijos = driver.find_element_by_xpath("//*[@id='empleoCliente_ingresosFijos']")
		ingresos_variables = driver.find_element_by_xpath("//*[@id='empleoCliente_ingresosVariables']")
		ingresos_fijos.send_keys("300000")
		ingresos_variables.send_keys("5000")
		ir_buro = driver.find_element_by_xpath("//*[@id='siguiente']")
		time.sleep(8)

	def tearDown(self):
		driver = self.driver
		cerrar = driver.find_element_by_xpath("//*[@id='userOptionsBtn']")
		cerrar.click()
		time.sleep(3)
		salir = driver.find_element_by_xpath("//*[@id='barraIconos']/div[2]/div/div[2]/div[3]/div[2]/ul/li[2]/ul/li[3]/a")
		salir.click()
		self.driver.close()

if __name__ == '__main__':
	unittest.main()